# Generated by Django 4.0.4 on 2022-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='displayPicture',
            field=models.ImageField(default=' ', upload_to='DisplayPicture/'),
            preserve_default=False,
        ),
    ]
