# Generated by Django 4.0.4 on 2022-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
