# Generated by Django 4.0.6 on 2022-07-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
