# Generated by Django 4.0.6 on 2022-07-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
